from aiogram import types

from keyboards.default.menu_btn import menu
from loader import dp
from keyboards.default.kurslar import kurslar

@dp.message_handler(text="🎓 Kurslar")
async def habar(message: types.message):
    await message.answer("<b>Aynan qaysi yo'nalishdagi kursimiz haqida ma'lumot kerak?</b>", reply_markup=kurslar)

@dp.message_handler(text="🖥 Kompyuter savodxonligi")
async def komp(message: types.message):
    await message.answer("<b>🎓 Kurs: Kompyuter savodxonligi!\n\n📚 Texnologiyalar : Kompyuterning ichki va tashqi tuzilishi, Ishlash sxemasi, Word, Excel, Powerpoint, PDF hujjatlar, Ta'lim saytlari bilan ishlash, Rangli va rangsiz Printerlar bilan ishlash</b>\n\n👨🏻‍💻 Jarayon: Umumiy kurs 3 oy muddatni o'z ichiga olib, ushbu muddat ichida siz eng sodda kompyuter amallaridan tortib eng murakkablarigacha bemalol bajara olasiz. Bundan tashqari kursimizni A'Lo natijalar bilan tamomlasangiz, o'z sertifikatingizga ega bo'lgan holda kursni yakunlaysiz.\n\n🎁 Bonus : Kurs davomida Kompyuter bilimlaridan tashqari, o'quvchilar o'zlarida liderlik qobiliyati va ilm olish sirlarini ham rivojlantirib olishadi. Turli xil seminarlar, qiziqarli bahslar va real loyihalar barchasi sizni kutmoqda shoshiling! Darslarda o'zlarini ko'rsatgan, masalalarga o'zgacha yechim beradigan, o'z ustida ishlashdan to'xtamaydigan o'quvchilar 100% jamoaga taklif etiladi!")

@dp.message_handler(text="🌐 Web dasturlash")
async def web(message: types.message):
    await message.answer("<b>🎓 Kurs:  Web dasturlash!\n\n Bu kursimiz Frontend va Backend qismlarga bo'linadi.\n\n📚 Frontend : Bu kursimizda siz web saytlarning dizayn qismi bo'yicha barcha bilimlarni olasiz va real loyihalar bilan ishlaysiz!</b>\n\n📚 Texnologiyalar: HTML5, CSS3, Bootstrap4, SASS, Javascript, IT resume.\n\n<b>👨🏻‍💻 Jarayon: Umumiy kurs 4 oy muddatni o'z ichiga olib, shu muddat ichida siz eng sodda web sayt maketlaridan tortib eng murakkablarigacha bemalol yasay olasiz. Bundan tashqari bir qancha real online magazinlar dizayni ustida ishlaysiz, kurs so'ngida siz kursimizni A'Lo natijalar bilan tamomlasangiz, o'z sertifikatingiz va portfoliongizga ega bo'lgan holda kursni yakunlaysiz!\n\nDarslarda o'zlarini ko'rsatgan, masalalarga o'zgacha yechim beradigan, o'z ustida ishlashdan to'xtamaydigan o'quvchilar 100% jamoaga taklif etiladi!🎓  Backend : Bu kursimizda siz web saytlarning  dinamik qismi ustida ishlash bo'yicha barcha bilimlarni olasiz va real loyihalar ustida ishlaysiz!</b>\n\n📚 Texnologiyalar: Javascript, Python, php, SQL, Node.js, Yii2/Laravel, IT resume.\n\n👨🏻‍💻 Jarayon: Back end kursimiz 4 oy muddatni tashkil etadi, kurs davomida siz saytlarning dinamik qismi ustida ishlashni <b>Python, Javascript va php</b> dasturlash tilida o'rganasiz. Faqatgina dinamik saytlar emas, balki  online magazin va bir qancha dasturlarni  ham bemalol qura olish imkoniyatiga ega bo'lasiz.\n\n🎁 Bonus : Kurs davomida dasturlashdan tashqari, o'quvchilar o'zlarida liderlik qobiliyati va ilm olish sirlarini ham rivojlantirib olishadi. Turli xil seminarlar, qiziqarli bahslar, real loyihalar barchasi sizni kutmoqda shoshiling!\n\nDarslarda o'zlarini ko'rsatgan, masalalarga o'zgacha yechim beradigan, o'z ustida ishlashdan to'xtamaydigan o'quvchilar 100% jamoaga taklif etiladi!")

@dp.message_handler(text="📲 Android")
async def android(message:types.message):
    await message.answer("<b>🎓 Kurs: Android!\n\n Bu kursimizda siz Android va iOS bo'yicha barcha bilimlarga ega bo'lasiz!\n\n📚 Texnologiyalar : Flutter, Java, Swift\n\n👨🏻‍💻 Jarayon: Umumiy kurs 8 oy muddatni o'z ichiga olib, ushbu muddat ichida siz Android va iOS bo'yicha real loyihalar bilan ishlaysiz!. Bundan tashqari kursimiz yakunida siz kursimizni A'Lo natijalar bilan tamomlasangiz, o'z sertifikatingiz va portfoliongizga ega bo'lgan holda kursni yakunlaysiz!\n\n🎁 Bonus : Kurs davomida Kompyuter bilimlaridan tashqari, o'quvchilar o'zlarida liderlik qobiliyati va ilm olish sirlarini ham rivojlantirib olishadi. Turli xil seminarlar, qiziqarli bahslar va real loyihalar barchasi sizni kutmoqda shoshiling! Darslarda o'zlarini ko'rsatgan, masalalarga o'zgacha yechim beradigan, o'z ustida ishlashdan to'xtamaydigan o'quvchilar 100% jamoaga taklif etiladi!</b>")

@dp.message_handler(text="🌄 Grafik dizayner")
async def grafik(message: types.message):
    await message.answer("<b>🎓 Kurs: Grafik dizayner!\n\n Bu kursimizda siz grafik dizayn bo'yicha barcha bilimlarga ega bo'lasiz va real loyihalar bilan ishlaysiz!\n\n📚 Texnologiyalar : Photoshop, corelDRAW, Adobe illustrator, Logo, Reklama </b>\n\n👨🏻‍💻 Jarayon: Umumiy kurs 8 oy muddatni o'z ichiga olib, ushbu muddat ichida siz Grafik dizany bo'yicha barcha bilimlarni olib, real loyihalar bilan ishlaysiz!. Bundan tashqari kursimiz yakunida siz kursimizni A'Lo natijalar bilan tamomlasangiz, o'z sertifikatingiz va portfoliongizga ega bo'lgan holda kursni yakunlaysiz!\n\n🎁 Bonus : Kurs davomida Grafik dizayn bilimlaridan tashqari, o'quvchilar o'zlarida liderlik qobiliyati va ilm olish sirlarini ham rivojlantirib olishadi. Turli xil seminarlar, qiziqarli bahslar va real loyihalar barchasi sizni kutmoqda shoshiling! Darslarda o'zlarini ko'rsatgan, masalalarga o'zgacha yechim beradigan, o'z ustida ishlashdan to'xtamaydigan o'quvchilar 100% jamoaga taklif etiladi!")

@dp.message_handler(text="❇️ Telegram bot")
async def bot(message: types.message):
    await message.answer("<b>🎓 Kurs: Telegram bot!\n\n Bu kursimizda siz Telagram bot bo'yicha barcha bilimlarga ega bo'lasiz va real loyihalar bilan ishlaysiz!\n\n👨🏻‍💻 Jarayon: Umumiy kurs 2 oy muddatni o'z ichiga olib, shu muddat ichida siz Python dasturlash tili orqali telegram bot yaratishning eng sodda amallaridan tortib eng murakkablarigacha bemalol bajara olasiz.   Bundan tashqari kursimiz yakunida siz kursimizni A'Lo natijalar bilan tamomlasangiz, o'z sertifikatingiz va portfoliongizga ega bo'lgan holda kursni yakunlaysiz!\n\n🎁 Bonus: Kurs davomida Telegram bot bilimlaridan tashqari, o'quvchilar o'zlarida liderlik qobiliyati va ilm olish sirlarini ham rivojlantirib olishadi. Turli xil seminarlar, qiziqarli bahslar va real loyihalar barchasi sizni kutmoqda shoshiling! Darslarda o'zlarini ko'rsatgan, masalalarga o'zgacha yechim beradigan, o'z ustida ishlashdan to'xtamaydigan o'quvchilar 100% jamoaga taklif etiladi!\n\n📉 Qo'shimcha : O'zingizda hech qanday o'sish his qilmasangiz,  pulingiz 100 % qaytariladi.</b>")

@dp.message_handler(text="📈 SMM")
async def smm(message: types.message):
    await message.answer("<b>🎓 Kurs: SMM (Social Media Marketing )!\n\nBu kursimizda siz SMM bo'yicha barcha bilimlarga ega bo'lasiz va real loyihalar bilan ishlaysiz!\n\n📚 Texnologiya: SMM, Marketing, Ijtimoiy tarmoqlar, Videomontaj</b>\n\n👨🏻‍💻 Jarayon: Kurs 4 oy muddatni o'zi ichiga olgan holda siz  o'zingizda SMM bo'yicha barcha ko'nikmalar va bilimlarni shakllantirasiz!.  Bundan tashqari kursimiz yakunida siz kursimizni A'Lo natijalar bilan tamomlasangiz, o'z sertifikatingiz va portfoliongizga ega bo'lgan holda kursni yakunlaysiz!\n\n🎁 Bonus : Kurs davomida SMM dan tashqari, o'quvchilar o'zlarida liderlik qobiliyati va ilm olish sirlarini ham rivojlantirib olishadi. Turli xil seminarlar, qiziqarli bahslar, real loyihalar barchasi sizni kutmoqda shoshiling! Darslarda o'zlarini ko'rsatgan, masalalarga o'zgacha yechim beradigan, o'z ustida ishlashdan to'xtamaydigan o'quvchilar 100 % jamoaga taklif etiladi!")

@dp.message_handler(text="🏞 Photoshop")
async def photoshop(message: types.message):
    await message.answer("<b>🎓 Kurs: Photoshop!\n\n📚 Texnologiyalar : Photoshop, Logo, Reklama\n\n👨🏻‍💻 Jarayon: Umumiy kurs 3 oy muddatni o'z ichiga olib, shu muddat ichida siz eng sodda Photoshop amallaridan tortib eng murakkablarigacha bemalol bajara olasiz.  Bundan tashqari kursimiz yakunida siz kursimizni A'Lo natijalar bilan tamomlasangiz, o'z sertifikatingiz va portfoliongizga ega bo'lgan holda kursni yakunlaysiz!\n\n🎁 Bonus : Kurs davomida Photoshop bilimlaridandan tashqari, o'quvchilar o'zlarida liderlik qobiliyati va ilm olish sirlarini ham rivojlantirib olishadi. Turli xil seminarlar, qiziqarli bahslar  barchasi sizni kutmoqda shoshiling! Darslarda o'zlarini ko'rsatgan, masalalarga o'zgacha yechim beradigan, o'z ustida ishlashdan to'xtamaydigan o'quvchilar 100% jamoaga taklif etiladin!</b>")

@dp.message_handler(text="🏙 Sun`iy intellekt")
async def suniy(message: types.message):
    await message.answer("|<b>🎓 Kurs: Sun`iy intellekt!\n\nBu kursimizda siz Data Science va Sun'iy Intellekt bo'yicha barcha bilimlarga ega bo'lasiz va real loyihalar bilan ishlaysiz!\n\n📚 Texnologiya:  Python, Data Science va Sun'iy Intellekt\n\nBu kursimizda siz Python bo'yicha barcha bilimlarga ega bo'lasiz va real loyihalar bilan ishlaysiz!  Bundan tashqari kursimiz yakunida siz kursimizni A'Lo natijalar bilan tamomlasangiz, o'z sertifikatingiz va portfoliongizga ega bo'lgan holda kursni yakunlaysiz!</b>\n\n👨🏻‍💻 Jarayon: Kurs 8 oy muddatni tashkil etadi. Kurs davomida o'quvchilar Data Science va Sun'iy Intellektdan tashqari o'zlarida liderlik qobiliyati va ilm olish sirlarini ham rivojlantirib olishadi. Turli xil seminarlar, qiziqarli bahslar, real loyihalar barchasi sizni kutmoqda shoshiling! Darslarda o'zlarini ko'rsatgan, masalalarga o'zgacha yechim beradigan, o'z ustida ishlashdan to'xtamaydigan o'quvchilar 100 % jamoaga taklif etiladi!")

@dp.message_handler(text="🐍 Python")
async def python(message: types.message):
    await message.answer("<b>🎓 Kurs: Python!\n\n📚 Texnologiya:  Python!\n\nBu kursimizda siz Python bo'yicha barcha bilimlarga ega bo'lasiz va real loyihalar bilan ishlaysiz!</b>\n\n👨🏻‍💻 Jarayon: Kurs 5 oy muddatni tashkil etadi. Kurs davomida siz  telegram bot, Django da e-shop (online magazin), Bankomatlarning ishlash sxemasi va kodini yozish kabi ko'plab loyihalar ustida ishlaysiz.  Bundan tashqari kursimiz yakunida siz kursimizni A'Lo natijalar bilan tamomlasangiz, o'z sertifikatingiz va portfoliongizga ega bo'lgan holda kursni yakunlaysiz!\n\n🎁 Bonus : Kurs davomida o'quvchilar Pythondan tashqari o'zlarida liderlik qobiliyati va ilm olish sirlarini ham rivojlantirib olishadi. Turli xil seminarlar, qiziqarli bahslar, real loyihalar barchasi sizni kutmoqda shoshiling! Darslarda o'zlarini ko'rsatgan, masalalarga o'zgacha yechim beradigan, o'z ustida ishlashdan to'xtamaydigan o'quvchilar 100 % jamoaga taklif etiladi.!")

@dp.message_handler(text="🔙 Ortga qaytish")
async def orttga(message: types.Message):
    await message.answer("Sizga qanday yordam bera olishim mumkin?", reply_markup=menu)